development:
  adapter: postgresql
  encoding: unicode
  database: base_app_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
 # host: 10.1.0.8
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: base_app_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  #host: 10.1.0.8
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: base_app_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  #host: 10.1.0.8
  port: 5432# SQLite version 3.x